// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppearanceSettings } from "./AppearanceSettings";
import type { BehaviorSettings } from "./BehaviorSettings";
import type { Language } from "./Language";
import type { ModelPricing } from "./ModelPricing";
import type { Persona } from "./Persona";
import type { ProviderId } from "./ProviderId";
import type { ProviderProfile } from "./ProviderProfile";
import type { SidebarLayout } from "./SidebarLayout";
import type { Speed } from "./Speed";
import type { SystemSettings } from "./SystemSettings";

export type AppSettings = { schemaVersion: number, enabled: boolean, hotkey: string, personaId: string, customPersonas: Array<Persona>, languageTag: string, customLanguages: Array<Language>, translate: boolean, speed: Speed, activeProvider: ProviderId, providers: Array<ProviderProfile>, pricing: { [key in string]?: ModelPricing }, behavior: BehaviorSettings, system: SystemSettings, appearance: AppearanceSettings, sidebar: SidebarLayout, };
