// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSource } from "./InputSource";
import type { OutputMode } from "./OutputMode";

export type BehaviorSettings = { inputSource: InputSource, outputMode: OutputMode, minimizeToTray: boolean, showNotifications: boolean, playSound: boolean, autoCopyFixed: boolean, keepHistory: boolean, };
