// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityNote } from "./CapabilityNote";
import type { DisplayServer } from "./DisplayServer";
import type { HotkeyBackend } from "./HotkeyBackend";
import type { InjectionBackend } from "./InjectionBackend";

export type Capabilities = { displayServer: DisplayServer, canCaptureSelection: boolean, injection: InjectionBackend, hotkey: HotkeyBackend, notes: Array<CapabilityNote>, };
