// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NoteSeverity } from "./NoteSeverity";

export type CapabilityNote = { severity: NoteSeverity, title: string, detail: string, remedy: string | null, };
