// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffSegment } from "./DiffSegment";
import type { TokenUsage } from "./TokenUsage";

export type FixOutcome = { original: string, corrected: string, diff: Array<DiffSegment>, changed: boolean, usage: TokenUsage, provider: string, model: string, elapsedMs: number, };
