// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FixRecord = { id: number, timestamp: number, provider: string, model: string, personaId: string, languageTag: string, translate: boolean, inputTokens: number, outputTokens: number, originalChars: number, correctedChars: number, changed: boolean, elapsedMs: number, };
