// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SidebarCategory = { id: string, name: string, collapsed: boolean, items: Array<string>, };
