// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarCategory } from "./SidebarCategory";

export type SidebarLayout = { categories: Array<SidebarCategory>, };
