// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsage } from "./ModelUsage";
import type { UsagePeriod } from "./UsagePeriod";

export type UsageReport = { today: UsagePeriod, week: UsagePeriod, month: UsagePeriod, allTime: UsagePeriod, byModel: Array<ModelUsage>, since: number | null, };
