// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageSummary } from "../../../../../../apps/desktop/src/lib/bindings/UsageSummary";

export type UsagePeriod = { summary: UsageSummary, cost: number, partialPricing: boolean, };
